# Generated by Django 4.1 on 2022-10-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('username', models.TextField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('User_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('contactinfo', models.CharField(max_length=25)),
                ('pkgname', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('tripstatus', models.IntegerField(default=0)),
                ('trans_id', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('phn_no', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
                ('emergency_number', models.CharField(max_length=50)),
                ('gov_id', models.CharField(max_length=16)),
            ],
        ),
    ]
